### ISSUE TITLE
Support GHC 9.10

### ISSUE THREAD

**Issue by ulysses4ever** [phadej/rere#28]

**Comment by ulysses4ever** [comment]
Cabal can't remove allow-newer's because of this. Please, consider solving it.

**Comment by phadej** [comment]
I'm not using `rere` myself for anything, so it's not a priority. If anyone wants to take over the maintenance, please volunteer.

**Comment by ulysses4ever** [comment]
@phadej thank you for clarifying! Could you add me as a maintainer on Hackage (ArtemPelenitsyn) and here?

**Comment by phadej** [comment]
Not add, but take over. Full commitment, including moving the repository out of my account. So I don't need to worry about it at all.

**Comment by ulysses4ever** [comment]
I could remove you on Hackage after you add me there and move the repository under my account (or something like https://github.com/haskell-pkg-janitors) if you give me admin rights here. This will check all the boxes, right? The takeover process takes weeks, I'd rather not go through it. Although, if you think that's the only way forward, I'll have to do it, I guess...

**Comment by phadej** [comment]
I cannot move the repository because

> ulysses4ever/rere already exists

**Comment by ulysses4ever** [comment]
Oh, this thing with forks always hits me! I've just removed the fork, and it should be possible to move the original now.

**Comment by phadej** [comment]
> Repository transfer to ulysses4ever requested

--

What's your Hackage username, I'll add you there after the transfer is done

**Comment by ulysses4ever** [comment]
ArtemPelenitsyn

**Comment by phadej** [comment]
Added you as a maintainer on Hackage.

Be great!

**Comment by ulysses4ever** [comment]
Thanks!

**Comment by ulysses4ever** [comment]
Updated the base bound here and on Hackage.
